install:
  - pipenv install

dist: trusty
jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - make build
      - make deliver

    - stage: tests
      script:
      - make test
