services:
  - docker

script:
  - sudo apt-get update && sudo apt-get install python-pip 
  - sudo pip install pipenv
  - pipenv install
  - pipenv run pytest
  - sudo docker-compose up -d

deploy:
  provider: script
  script: ./starting_app.sh
  on:
    branch: continuous-deploy

