version: '3'

services:

  # serveur applicatif
  python:
    build: .
    restart: always
    networks:
      test_network:
    volumes:
      - .:/api_flat/.
    working_dir: /api_flat
    command: bash -c 'pipenv install; pipenv run python database_gen.py; pipenv run python api_flat.py'
    depends_on:
      - db
    ports:
      - 5000:5000

  # base de données
  db:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: youwillneverguess
      POSTGRES_DB: api_flat_dev
    networks:
      test_network:
    ports:
      - 5432
    volumes:
      - dev_data:/var/lib/postgresql/data/

# permet de configurer le réseau "virtuel" dans le docker engine
networks:
  test_network:

# permet de créer un dossier dossier partagé entre le container et la machine hôte (sauvegarde db)
volumes:
  dev_data:
