version: "3.4"

services:
  db:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: app
      
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
  
  app:
    build: .
    restart: "no"
   # volumes:
   #   - factures_data:/app/factures
    ports:
      - "5000:5000"
   #scale: 2
    networks:
      - backend

  #proxy:
    #image:
    #networks:
     #- backend

volumes:
  postgresql_data:

#on déclare un volume pour stocker les facturettes (voir où Flask enregistre les datas)
#volumes:
# factures_data:

#on déclare un réseau pour lier les différents conteneurs entre eux
networks:
  backend:
